#ifndef __IICCTRL_DEFS_H__
#define __IICCTRL_DEFS_H__


#define VIDEO_RESOLUTION_1080P 7
#define HDMI_I2C_BASE_ADDR 0
#define HDMI_VTC_DEVICE_ID 1
#define HDMI_VDMA_DEVICE_ID 2
#define HDMI_DISPLAY_MEM_BASE_ADDR 3

#define IIC_STATUS_TIMEOUT 10000

#define ADV7511_ADDR   0x72
#define CARRIER_HDMI_OUT_CONFIG_LEN  (40)

#endif
