# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_property board em.avnet.com:zynq:zed:d [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property ip_repo_paths /home/agilehw/agile-codev-platform/hw/Vivado/hwIPBlock [current_fileset]
add_files /home/agilehw/agile-codev-platform/hw/Vivado/hwIPBlock/hwIPBlock.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files /home/agilehw/agile-codev-platform/hw/Vivado/hwIPBlock/hwIPBlock.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
set_property use_blackbox_stub false [get_files /home/agilehw/agile-codev-platform/hw/Vivado/hwIPBlock/hwIPBlock.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]

read_ip /home/agilehw/agile-codev-platform/hw/Vivado/hwIPBlock/hwIPBlock.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files /home/agilehw/agile-codev-platform/hw/Vivado/hwIPBlock/hwIPBlock.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files /home/agilehw/agile-codev-platform/hw/Vivado/hwIPBlock/hwIPBlock.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci]

read_verilog -sv {
  /home/agilehw/agile-codev-platform/hw/Vivado/hwIPBlock/hwIPBlock.srcs/sources_1/new/qpram.sv
  /home/agilehw/agile-codev-platform/hw/Vivado/hwIPBlock/hwIPBlock.srcs/sources_1/new/pixelProcessor_IO.sv
  /home/agilehw/agile-codev-platform/hw/Vivado/hwIPBlock/hwIPBlock.srcs/sources_1/new/pixelProcessor_s1.sv
}
read_verilog {
  /home/agilehw/agile-codev-platform/hw/Vivado/hwIPBlock/hwIPBlock.srcs/sources_1/new/agileHwBlock.v
  /home/agilehw/agile-codev-platform/hw/Vivado/clk_wiz/clk_wiz_0/clk_wiz_0_stub.v
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/agilehw/agile-codev-platform/hw/Vivado/hwIPBlock/hwIPBlock.data/wt [current_project]
set_property parent.project_dir /home/agilehw/agile-codev-platform/hw/Vivado/hwIPBlock [current_project]
synth_design -top agileHWBlock -part xc7z020clg484-1
write_checkpoint agileHWBlock.dcp
report_utilization -file agileHWBlock_utilization_synth.rpt -pb agileHWBlock_utilization_synth.pb
