# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/zedboard_hdmi_display.xdc

# Block Designs: bd/MainDesign/MainDesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign || ORIG_REF_NAME==MainDesign}]

# IP: bd/MainDesign/ip/MainDesign_processing_system7_0_0/MainDesign_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_processing_system7_0_0 || ORIG_REF_NAME==MainDesign_processing_system7_0_0}]

# IP: bd/MainDesign/ip/MainDesign_axi_iic_0_0/MainDesign_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_axi_iic_0_0 || ORIG_REF_NAME==MainDesign_axi_iic_0_0}]

# IP: bd/MainDesign/ip/MainDesign_processing_system7_0_axi_periph_0/MainDesign_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==MainDesign_processing_system7_0_axi_periph_0}]

# IP: bd/MainDesign/ip/MainDesign_proc_sys_reset_0/MainDesign_proc_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_proc_sys_reset_0 || ORIG_REF_NAME==MainDesign_proc_sys_reset_0}]

# IP: bd/MainDesign/ip/MainDesign_clk_wiz_0_0/MainDesign_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_clk_wiz_0_0 || ORIG_REF_NAME==MainDesign_clk_wiz_0_0}]

# IP: bd/MainDesign/ip/MainDesign_axi_mem_intercon_1/MainDesign_axi_mem_intercon_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_axi_mem_intercon_1 || ORIG_REF_NAME==MainDesign_axi_mem_intercon_1}]

# IP: bd/MainDesign/ip/MainDesign_axi_vdma_0_0/MainDesign_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_axi_vdma_0_0 || ORIG_REF_NAME==MainDesign_axi_vdma_0_0}]

# IP: bd/MainDesign/ip/MainDesign_axis_subset_converter_0_0/MainDesign_axis_subset_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_axis_subset_converter_0_0 || ORIG_REF_NAME==MainDesign_axis_subset_converter_0_0}]

# IP: bd/MainDesign/ip/MainDesign_gnd_0/MainDesign_gnd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_gnd_0 || ORIG_REF_NAME==MainDesign_gnd_0}]

# IP: bd/MainDesign/ip/MainDesign_proc_sys_reset_1/MainDesign_proc_sys_reset_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_proc_sys_reset_1 || ORIG_REF_NAME==MainDesign_proc_sys_reset_1}]

# IP: bd/MainDesign/ip/MainDesign_v_axi4s_vid_out_0_0/MainDesign_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==MainDesign_v_axi4s_vid_out_0_0}]

# IP: bd/MainDesign/ip/MainDesign_v_cresample_0_1/MainDesign_v_cresample_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_v_cresample_0_1 || ORIG_REF_NAME==MainDesign_v_cresample_0_1}]

# IP: bd/MainDesign/ip/MainDesign_v_rgb2ycrcb_0_0/MainDesign_v_rgb2ycrcb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_v_rgb2ycrcb_0_0 || ORIG_REF_NAME==MainDesign_v_rgb2ycrcb_0_0}]

# IP: bd/MainDesign/ip/MainDesign_v_tc_0_0/MainDesign_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_v_tc_0_0 || ORIG_REF_NAME==MainDesign_v_tc_0_0}]

# IP: bd/MainDesign/ip/MainDesign_vcc_1/MainDesign_vcc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_vcc_1 || ORIG_REF_NAME==MainDesign_vcc_1}]

# IP: bd/MainDesign/ip/MainDesign_zed_hdmi_out_0_0/MainDesign_zed_hdmi_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_zed_hdmi_out_0_0 || ORIG_REF_NAME==MainDesign_zed_hdmi_out_0_0}]

# IP: bd/MainDesign/ip/MainDesign_xbar_2/MainDesign_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xbar_2 || ORIG_REF_NAME==MainDesign_xbar_2}]

# IP: bd/MainDesign/ip/MainDesign_agileHWBlock_0_9/MainDesign_agileHWBlock_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_agileHWBlock_0_9 || ORIG_REF_NAME==MainDesign_agileHWBlock_0_9}]

# IP: bd/MainDesign/ip/MainDesign_auto_pc_83/MainDesign_auto_pc_83.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_auto_pc_83 || ORIG_REF_NAME==MainDesign_auto_pc_83}]

# IP: bd/MainDesign/ip/MainDesign_auto_pc_84/MainDesign_auto_pc_84.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_auto_pc_84 || ORIG_REF_NAME==MainDesign_auto_pc_84}]

# XDC: bd/MainDesign/ip/MainDesign_processing_system7_0_0/MainDesign_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MainDesign_processing_system7_0_0 || ORIG_REF_NAME==MainDesign_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/MainDesign/ip/MainDesign_axi_iic_0_0/MainDesign_axi_iic_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MainDesign_axi_iic_0_0 || ORIG_REF_NAME==MainDesign_axi_iic_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MainDesign/ip/MainDesign_axi_iic_0_0/MainDesign_axi_iic_0_0_ooc.xdc

# XDC: bd/MainDesign/ip/MainDesign_proc_sys_reset_0/MainDesign_proc_sys_reset_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MainDesign_proc_sys_reset_0 || ORIG_REF_NAME==MainDesign_proc_sys_reset_0}] {/U0 }]/U0 ]]

# XDC: bd/MainDesign/ip/MainDesign_proc_sys_reset_0/MainDesign_proc_sys_reset_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MainDesign_proc_sys_reset_0 || ORIG_REF_NAME==MainDesign_proc_sys_reset_0}] {/U0 }]/U0 ]]

# XDC: bd/MainDesign/ip/MainDesign_proc_sys_reset_0/MainDesign_proc_sys_reset_0_ooc.xdc

# XDC: bd/MainDesign/ip/MainDesign_clk_wiz_0_0/MainDesign_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MainDesign_clk_wiz_0_0 || ORIG_REF_NAME==MainDesign_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/MainDesign/ip/MainDesign_clk_wiz_0_0/MainDesign_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MainDesign_clk_wiz_0_0 || ORIG_REF_NAME==MainDesign_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/MainDesign/ip/MainDesign_clk_wiz_0_0/MainDesign_clk_wiz_0_0_OOC.xdc

# XDC: bd/MainDesign/ip/MainDesign_axi_vdma_0_0/MainDesign_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MainDesign_axi_vdma_0_0 || ORIG_REF_NAME==MainDesign_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MainDesign/ip/MainDesign_axi_vdma_0_0/MainDesign_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MainDesign_axi_vdma_0_0 || ORIG_REF_NAME==MainDesign_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MainDesign/ip/MainDesign_axi_vdma_0_0/MainDesign_axi_vdma_0_0_ooc.xdc

# XDC: bd/MainDesign/ip/MainDesign_axis_subset_converter_0_0/MainDesign_axis_subset_converter_0_0_ooc.xdc

# XDC: bd/MainDesign/ip/MainDesign_proc_sys_reset_1/MainDesign_proc_sys_reset_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MainDesign_proc_sys_reset_1 || ORIG_REF_NAME==MainDesign_proc_sys_reset_1}] {/U0 }]/U0 ]]

# XDC: bd/MainDesign/ip/MainDesign_proc_sys_reset_1/MainDesign_proc_sys_reset_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MainDesign_proc_sys_reset_1 || ORIG_REF_NAME==MainDesign_proc_sys_reset_1}] {/U0 }]/U0 ]]

# XDC: bd/MainDesign/ip/MainDesign_proc_sys_reset_1/MainDesign_proc_sys_reset_1_ooc.xdc

# XDC: bd/MainDesign/ip/MainDesign_v_axi4s_vid_out_0_0/MainDesign_v_axi4s_vid_out_0_0_ooc.xdc

# XDC: bd/MainDesign/ip/MainDesign_v_axi4s_vid_out_0_0/MainDesign_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MainDesign_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==MainDesign_v_axi4s_vid_out_0_0}] {/inst }]/inst ]]

# XDC: bd/MainDesign/ip/MainDesign_v_cresample_0_1/MainDesign_v_cresample_0_1_ooc.xdc

# XDC: bd/MainDesign/ip/MainDesign_v_cresample_0_1/MainDesign_v_cresample_0_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MainDesign_v_cresample_0_1 || ORIG_REF_NAME==MainDesign_v_cresample_0_1}] {/U0 }]/U0 ]]

# XDC: bd/MainDesign/ip/MainDesign_v_rgb2ycrcb_0_0/MainDesign_v_rgb2ycrcb_0_0_ooc.xdc

# XDC: bd/MainDesign/ip/MainDesign_v_rgb2ycrcb_0_0/MainDesign_v_rgb2ycrcb_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MainDesign_v_rgb2ycrcb_0_0 || ORIG_REF_NAME==MainDesign_v_rgb2ycrcb_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MainDesign/ip/MainDesign_v_tc_0_0/MainDesign_v_tc_0_0_ooc.xdc

# XDC: bd/MainDesign/ip/MainDesign_v_tc_0_0/MainDesign_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MainDesign_v_tc_0_0 || ORIG_REF_NAME==MainDesign_v_tc_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MainDesign/ip/MainDesign_xbar_2/MainDesign_xbar_2_ooc.xdc

# XDC: bd/MainDesign/MainDesign_ooc.xdc
