# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/zedboard_hdmi_display.xdc

# Block Designs: bd/FinalDesign/FinalDesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FinalDesign || ORIG_REF_NAME==FinalDesign}]

# IP: bd/FinalDesign/ip/FinalDesign_processing_system7_0_1/FinalDesign_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FinalDesign_processing_system7_0_1 || ORIG_REF_NAME==FinalDesign_processing_system7_0_1}]

# IP: bd/FinalDesign/ip/FinalDesign_axi_iic_0_1/FinalDesign_axi_iic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FinalDesign_axi_iic_0_1 || ORIG_REF_NAME==FinalDesign_axi_iic_0_1}]

# IP: bd/FinalDesign/ip/FinalDesign_processing_system7_0_axi_periph_1/FinalDesign_processing_system7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FinalDesign_processing_system7_0_axi_periph_1 || ORIG_REF_NAME==FinalDesign_processing_system7_0_axi_periph_1}]

# IP: bd/FinalDesign/ip/FinalDesign_proc_sys_reset_1/FinalDesign_proc_sys_reset_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FinalDesign_proc_sys_reset_1 || ORIG_REF_NAME==FinalDesign_proc_sys_reset_1}]

# IP: bd/FinalDesign/ip/FinalDesign_clk_wiz_0_0/FinalDesign_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FinalDesign_clk_wiz_0_0 || ORIG_REF_NAME==FinalDesign_clk_wiz_0_0}]

# IP: bd/FinalDesign/ip/FinalDesign_axi_mem_intercon_2/FinalDesign_axi_mem_intercon_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FinalDesign_axi_mem_intercon_2 || ORIG_REF_NAME==FinalDesign_axi_mem_intercon_2}]

# IP: bd/FinalDesign/ip/FinalDesign_axi_vdma_0_0/FinalDesign_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FinalDesign_axi_vdma_0_0 || ORIG_REF_NAME==FinalDesign_axi_vdma_0_0}]

# IP: bd/FinalDesign/ip/FinalDesign_axis_subset_converter_0_0/FinalDesign_axis_subset_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FinalDesign_axis_subset_converter_0_0 || ORIG_REF_NAME==FinalDesign_axis_subset_converter_0_0}]

# IP: bd/FinalDesign/ip/FinalDesign_gnd_0/FinalDesign_gnd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FinalDesign_gnd_0 || ORIG_REF_NAME==FinalDesign_gnd_0}]

# IP: bd/FinalDesign/ip/FinalDesign_proc_sys_reset_2/FinalDesign_proc_sys_reset_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FinalDesign_proc_sys_reset_2 || ORIG_REF_NAME==FinalDesign_proc_sys_reset_2}]

# IP: bd/FinalDesign/ip/FinalDesign_v_axi4s_vid_out_0_0/FinalDesign_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FinalDesign_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==FinalDesign_v_axi4s_vid_out_0_0}]

# IP: bd/FinalDesign/ip/FinalDesign_v_cresample_0_0/FinalDesign_v_cresample_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FinalDesign_v_cresample_0_0 || ORIG_REF_NAME==FinalDesign_v_cresample_0_0}]

# IP: bd/FinalDesign/ip/FinalDesign_v_rgb2ycrcb_0_0/FinalDesign_v_rgb2ycrcb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FinalDesign_v_rgb2ycrcb_0_0 || ORIG_REF_NAME==FinalDesign_v_rgb2ycrcb_0_0}]

# IP: bd/FinalDesign/ip/FinalDesign_v_tc_0_0/FinalDesign_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FinalDesign_v_tc_0_0 || ORIG_REF_NAME==FinalDesign_v_tc_0_0}]

# IP: bd/FinalDesign/ip/FinalDesign_vcc_1/FinalDesign_vcc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FinalDesign_vcc_1 || ORIG_REF_NAME==FinalDesign_vcc_1}]

# IP: bd/FinalDesign/ip/FinalDesign_zed_hdmi_out_0_0/FinalDesign_zed_hdmi_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FinalDesign_zed_hdmi_out_0_0 || ORIG_REF_NAME==FinalDesign_zed_hdmi_out_0_0}]

# IP: bd/FinalDesign/ip/FinalDesign_xbar_3/FinalDesign_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FinalDesign_xbar_3 || ORIG_REF_NAME==FinalDesign_xbar_3}]

# IP: bd/FinalDesign/ip/FinalDesign_agileHWBlock_0_1/FinalDesign_agileHWBlock_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FinalDesign_agileHWBlock_0_1 || ORIG_REF_NAME==FinalDesign_agileHWBlock_0_1}]

# IP: bd/FinalDesign/ip/FinalDesign_auto_pc_7/FinalDesign_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FinalDesign_auto_pc_7 || ORIG_REF_NAME==FinalDesign_auto_pc_7}]

# IP: bd/FinalDesign/ip/FinalDesign_auto_pc_8/FinalDesign_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FinalDesign_auto_pc_8 || ORIG_REF_NAME==FinalDesign_auto_pc_8}]

# XDC: bd/FinalDesign/ip/FinalDesign_processing_system7_0_1/FinalDesign_processing_system7_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FinalDesign_processing_system7_0_1 || ORIG_REF_NAME==FinalDesign_processing_system7_0_1}] {/inst }]/inst ]]

# XDC: bd/FinalDesign/ip/FinalDesign_axi_iic_0_1/FinalDesign_axi_iic_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FinalDesign_axi_iic_0_1 || ORIG_REF_NAME==FinalDesign_axi_iic_0_1}] {/U0 }]/U0 ]]

# XDC: bd/FinalDesign/ip/FinalDesign_axi_iic_0_1/FinalDesign_axi_iic_0_1_ooc.xdc

# XDC: bd/FinalDesign/ip/FinalDesign_proc_sys_reset_1/FinalDesign_proc_sys_reset_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FinalDesign_proc_sys_reset_1 || ORIG_REF_NAME==FinalDesign_proc_sys_reset_1}] {/U0 }]/U0 ]]

# XDC: bd/FinalDesign/ip/FinalDesign_proc_sys_reset_1/FinalDesign_proc_sys_reset_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FinalDesign_proc_sys_reset_1 || ORIG_REF_NAME==FinalDesign_proc_sys_reset_1}] {/U0 }]/U0 ]]

# XDC: bd/FinalDesign/ip/FinalDesign_proc_sys_reset_1/FinalDesign_proc_sys_reset_1_ooc.xdc

# XDC: bd/FinalDesign/ip/FinalDesign_clk_wiz_0_0/FinalDesign_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FinalDesign_clk_wiz_0_0 || ORIG_REF_NAME==FinalDesign_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/FinalDesign/ip/FinalDesign_clk_wiz_0_0/FinalDesign_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FinalDesign_clk_wiz_0_0 || ORIG_REF_NAME==FinalDesign_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/FinalDesign/ip/FinalDesign_clk_wiz_0_0/FinalDesign_clk_wiz_0_0_OOC.xdc

# XDC: bd/FinalDesign/ip/FinalDesign_axi_vdma_0_0/FinalDesign_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FinalDesign_axi_vdma_0_0 || ORIG_REF_NAME==FinalDesign_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/FinalDesign/ip/FinalDesign_axi_vdma_0_0/FinalDesign_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FinalDesign_axi_vdma_0_0 || ORIG_REF_NAME==FinalDesign_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/FinalDesign/ip/FinalDesign_axi_vdma_0_0/FinalDesign_axi_vdma_0_0_ooc.xdc

# XDC: bd/FinalDesign/ip/FinalDesign_axis_subset_converter_0_0/FinalDesign_axis_subset_converter_0_0_ooc.xdc

# XDC: bd/FinalDesign/ip/FinalDesign_proc_sys_reset_2/FinalDesign_proc_sys_reset_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FinalDesign_proc_sys_reset_2 || ORIG_REF_NAME==FinalDesign_proc_sys_reset_2}] {/U0 }]/U0 ]]

# XDC: bd/FinalDesign/ip/FinalDesign_proc_sys_reset_2/FinalDesign_proc_sys_reset_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FinalDesign_proc_sys_reset_2 || ORIG_REF_NAME==FinalDesign_proc_sys_reset_2}] {/U0 }]/U0 ]]

# XDC: bd/FinalDesign/ip/FinalDesign_proc_sys_reset_2/FinalDesign_proc_sys_reset_2_ooc.xdc

# XDC: bd/FinalDesign/ip/FinalDesign_v_axi4s_vid_out_0_0/FinalDesign_v_axi4s_vid_out_0_0_ooc.xdc

# XDC: bd/FinalDesign/ip/FinalDesign_v_axi4s_vid_out_0_0/FinalDesign_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FinalDesign_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==FinalDesign_v_axi4s_vid_out_0_0}] {/inst }]/inst ]]

# XDC: bd/FinalDesign/ip/FinalDesign_v_cresample_0_0/FinalDesign_v_cresample_0_0_ooc.xdc

# XDC: bd/FinalDesign/ip/FinalDesign_v_cresample_0_0/FinalDesign_v_cresample_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FinalDesign_v_cresample_0_0 || ORIG_REF_NAME==FinalDesign_v_cresample_0_0}] {/U0 }]/U0 ]]

# XDC: bd/FinalDesign/ip/FinalDesign_v_rgb2ycrcb_0_0/FinalDesign_v_rgb2ycrcb_0_0_ooc.xdc

# XDC: bd/FinalDesign/ip/FinalDesign_v_rgb2ycrcb_0_0/FinalDesign_v_rgb2ycrcb_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FinalDesign_v_rgb2ycrcb_0_0 || ORIG_REF_NAME==FinalDesign_v_rgb2ycrcb_0_0}] {/U0 }]/U0 ]]

# XDC: bd/FinalDesign/ip/FinalDesign_v_tc_0_0/FinalDesign_v_tc_0_0_ooc.xdc

# XDC: bd/FinalDesign/ip/FinalDesign_v_tc_0_0/FinalDesign_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FinalDesign_v_tc_0_0 || ORIG_REF_NAME==FinalDesign_v_tc_0_0}] {/U0 }]/U0 ]]

# XDC: bd/FinalDesign/ip/FinalDesign_xbar_3/FinalDesign_xbar_3_ooc.xdc

# XDC: bd/FinalDesign/ip/FinalDesign_auto_pc_7/FinalDesign_auto_pc_7_ooc.xdc

# XDC: bd/FinalDesign/ip/FinalDesign_auto_pc_8/FinalDesign_auto_pc_8_ooc.xdc

# XDC: bd/FinalDesign/FinalDesign_ooc.xdc
