# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0

read_ip /home/agilehw/agile-codev-platform/hw/Vivado/blk_mem/blk_mem_gen_0/blk_mem_gen_0.xci
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files /home/agilehw/agile-codev-platform/hw/Vivado/blk_mem/blk_mem_gen_0/blk_mem_gen_0.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/agilehw/agile-codev-platform/hw/Vivado/blk_mem/managed_ip_project/managed_ip_project.data/wt [current_project]
set_property parent.project_dir /home/agilehw/agile-codev-platform/hw/Vivado/blk_mem/managed_ip_project [current_project]
synth_design -top blk_mem_gen_0 -part xc7z020clg484-1 -mode out_of_context

rename_ref -prefix_all blk_mem_gen_0
write_checkpoint -noxdef blk_mem_gen_0.dcp
report_utilization -file blk_mem_gen_0_utilization_synth.rpt -pb blk_mem_gen_0_utilization_synth.pb
if { [catch {
  file copy -force /home/agilehw/agile-codev-platform/hw/Vivado/blk_mem/managed_ip_project/managed_ip_project.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp /home/agilehw/agile-codev-platform/hw/Vivado/blk_mem/blk_mem_gen_0/blk_mem_gen_0.dcp
  write_verilog -force -mode synth_stub /home/agilehw/agile-codev-platform/hw/Vivado/blk_mem/blk_mem_gen_0/blk_mem_gen_0_stub.v
  write_verilog -force -mode funcsim /home/agilehw/agile-codev-platform/hw/Vivado/blk_mem/blk_mem_gen_0/blk_mem_gen_0_funcsim.v
  write_vhdl -force -mode funcsim /home/agilehw/agile-codev-platform/hw/Vivado/blk_mem/blk_mem_gen_0/blk_mem_gen_0_funcsim.vhdl
} _RESULT ] } { 
  puts "Critical Warning: Unable to successfully create or copy supporting IP files."
}
