# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/agilehw/agile-codev-platform/hw/Vivado/sdpram/sdpram30x15360/sdpram30x15360.xci
# IP: The module: 'sdpram30x15360' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/agilehw/agile-codev-platform/hw/Vivado/sdpram/sdpram30x15360/sdpram30x15360_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sdpram30x15360'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/agilehw/agile-codev-platform/hw/Vivado/sdpram/sdpram30x15360/sdpram30x15360.xci
# IP: The module: 'sdpram30x15360' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/agilehw/agile-codev-platform/hw/Vivado/sdpram/sdpram30x15360/sdpram30x15360_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sdpram30x15360'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
