# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0

read_ip /home/agilehw/agile-codev-platform/hw/Vivado/sdpram/sdpram30x15360/sdpram30x15360.xci
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files /home/agilehw/agile-codev-platform/hw/Vivado/sdpram/sdpram30x15360/sdpram30x15360.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/agilehw/agile-codev-platform/hw/Vivado/sdpram/managed_ip_project/managed_ip_project.data/wt [current_project]
set_property parent.project_dir /home/agilehw/agile-codev-platform/hw/Vivado/sdpram/managed_ip_project [current_project]
synth_design -top sdpram30x15360 -part xc7vx485tffg1157-1 -mode out_of_context

rename_ref -prefix_all sdpram30x15360
write_checkpoint -noxdef sdpram30x15360.dcp
report_utilization -file sdpram30x15360_utilization_synth.rpt -pb sdpram30x15360_utilization_synth.pb
if { [catch {
  file copy -force /home/agilehw/agile-codev-platform/hw/Vivado/sdpram/managed_ip_project/managed_ip_project.runs/sdpram30x15360_synth_1/sdpram30x15360.dcp /home/agilehw/agile-codev-platform/hw/Vivado/sdpram/sdpram30x15360/sdpram30x15360.dcp
  write_verilog -force -mode synth_stub /home/agilehw/agile-codev-platform/hw/Vivado/sdpram/sdpram30x15360/sdpram30x15360_stub.v
  write_verilog -force -mode funcsim /home/agilehw/agile-codev-platform/hw/Vivado/sdpram/sdpram30x15360/sdpram30x15360_funcsim.v
  write_vhdl -force -mode funcsim /home/agilehw/agile-codev-platform/hw/Vivado/sdpram/sdpram30x15360/sdpram30x15360_funcsim.vhdl
} _RESULT ] } { 
  puts "Critical Warning: Unable to successfully create or copy supporting IP files."
}
